# Generated by Django 5.1.3 on 2025-01-27 14:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crm_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_id', models.CharField(max_length=255)),
                ('pipeline_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=255)),
                ('status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('group', models.CharField(max_length=100)),
                ('lead_place', models.CharField(max_length=255)),
                ('lead_istochnik', models.CharField(max_length=255)),
                ('etiroz_sababi', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('closed_at', models.DateTimeField(null=True)),
                ('lead_active_time', models.CharField(max_length=255)),
                ('change_time_status', models.DateTimeField(blank=True, default=datetime.datetime(1111, 1, 1, 0, 0), null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='crm.crm_users')),
                ('responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_user', to='crm.crm_users')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_by', to='crm.crm_users')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=255)),
                ('status_name', models.CharField(max_length=255)),
                ('pipeline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.pipeline')),
            ],
        ),
        migrations.CreateModel(
            name='Lead_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status_time', models.DateTimeField()),
                ('new_status_time', models.DateTimeField()),
                ('total_time_status', models.CharField(max_length=500)),
                ('lead_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
                ('new_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_updated_by', to='crm.crm_users')),
                ('old_updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_updated_by', to='crm.crm_users')),
                ('new_pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_pipeline', to='crm.pipeline')),
                ('old_pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_pipeline', to='crm.pipeline')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_status', to='crm.status')),
                ('old_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_status', to='crm.status')),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.status'),
        ),
    ]
