# Generated by Django 5.1.3 on 2024-12-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=100)),
                ('lead_name', models.CharField(max_length=255)),
                ('responsible_user', models.CharField(max_length=255)),
                ('created_by', models.CharField(max_length=100)),
                ('group', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pipeline', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('last_time_sync', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
