# Generated by Django 5.1.3 on 2025-01-23 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead_history',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='lead_history',
            name='new_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_updated_by', to='crm.crm_users'),
        ),
        migrations.AddField(
            model_name='lead_history',
            name='old_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_updated_by', to='crm.crm_users'),
        ),
    ]
