# Generated by Django 5.1.3 on 2024-12-27 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crm_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('change_time_status', models.DateTimeField()),
                ('responsible_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.crm_users')),
            ],
        ),
        migrations.CreateModel(
            name='Lead_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status_time', models.DateTimeField(blank=True, null=True)),
                ('new_status_time', models.DateTimeField(blank=True, null=True)),
                ('total_time_status', models.DateTimeField()),
                ('lead_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pipeline_id', models.CharField(max_length=255)),
                ('pipeline_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=255)),
                ('status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Leads_status',
        ),
        migrations.AddField(
            model_name='lead_history',
            name='new_pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_pipeline', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='lead_history',
            name='old_pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_pipeline', to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.pipeline'),
        ),
        migrations.AddField(
            model_name='lead_history',
            name='new_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_status', to='crm.status'),
        ),
        migrations.AddField(
            model_name='lead_history',
            name='old_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_status', to='crm.status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.status'),
        ),
    ]
