# Generated by Django 5.1.3 on 2025-01-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='etiroz_sababi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_istochnik',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_place',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
