# Generated by Django 5.1.3 on 2024-12-27 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_crm_users_lead_lead_history_pipeline_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='pipeline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.pipeline'),
        ),
    ]
