# Generated by Django 5.1.3 on 2025-01-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_status_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
