# Generated by Django 5.1.3 on 2025-01-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_status_status_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.CharField(max_length=255)),
                ('status_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='status',
            name='status_id',
            field=models.CharField(max_length=255),
        ),
    ]
