# Generated by Django 5.1.3 on 2025-01-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_uniquestatus_alter_status_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='change_time_status',
            field=models.DateTimeField(null=True),
        ),
    ]
